name: build
on: [push]
jobs:
   build-ubuntu:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Cache protoc
         uses: actions/cache@v1
         with:
           path: protobuf
           key: ${{ runner.os }}-protoc-cache

       - name: Install dependencies
         run: ./install

       - name: make
         run: make
